/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrea
 */
public class taskFrame2 extends javax.swing.JFrame {
    private TaskGroup taskGroup;
    private tasksFrame tasksFrame;
    private User user;

    
    /**
     * Creates new form taskFrame2
     */
    public taskFrame2() {
        initComponents();
    }

    taskFrame2(TaskGroup taskGroup, User user) {
        this.taskGroup = taskGroup;
        this.user = user;
        initComponents();
        taskGroupNameLabel.setText(taskGroup.getCategoryName());
        taskGroupDLabel.setText(taskGroup.getCategoryDescription());
        this.printTasksTextArea.setText(taskGroup.printTask());
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoryLabel = new javax.swing.JLabel();
        taskGroupNameLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JLabel();
        taskGroupDescriptionLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        printTasksTextArea = new javax.swing.JTextArea();
        addTaskButton = new javax.swing.JButton();
        taskNameField = new javax.swing.JTextField();
        taskDescriptionField = new javax.swing.JTextField();
        taskPrioritySlider = new javax.swing.JSlider();
        dueDateField = new javax.swing.JTextField();
        sortTasksButton = new javax.swing.JButton();
        markCompleteButton = new javax.swing.JButton();
        deleteTaskButton = new javax.swing.JButton();
        addTaskNameLabel = new javax.swing.JLabel();
        AddTaskkDescriptionLabel = new javax.swing.JLabel();
        taskPriorityLabel = new javax.swing.JLabel();
        taskDueDateLabel = new javax.swing.JLabel();
        addTasksLabel = new javax.swing.JLabel();
        editTasksLabel = new javax.swing.JLabel();
        searchTaskLabel = new javax.swing.JLabel();
        searchTaskField = new javax.swing.JTextField();
        taskGroupDLabel = new javax.swing.JLabel();
        taskGroupHeaderLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("To Do List | Taks Group |");

        categoryLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
        categoryLabel.setText("Category: ");

        taskGroupNameLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N

        descriptionLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
        descriptionLabel.setText("Description: ");

        taskGroupDescriptionLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N

        printTasksTextArea.setEditable(false);
        printTasksTextArea.setColumns(20);
        printTasksTextArea.setRows(5);
        jScrollPane2.setViewportView(printTasksTextArea);

        addTaskButton.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        addTaskButton.setText("Add Task");
        addTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskButtonActionPerformed(evt);
            }
        });

        taskNameField.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        taskNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskNameFieldActionPerformed(evt);
            }
        });

        taskDescriptionField.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N

        taskPrioritySlider.setMajorTickSpacing(1);
        taskPrioritySlider.setMaximum(10);
        taskPrioritySlider.setMinimum(1);
        taskPrioritySlider.setMinorTickSpacing(1);
        taskPrioritySlider.setPaintLabels(true);
        taskPrioritySlider.setPaintTicks(true);
        taskPrioritySlider.setSnapToTicks(true);
        taskPrioritySlider.setValue(5);

        dueDateField.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N

        sortTasksButton.setText("Sort Tasks");
        sortTasksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortTasksButtonActionPerformed(evt);
            }
        });

        markCompleteButton.setText("Mark Task As Complete");
        markCompleteButton.setEnabled(false);
        markCompleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markCompleteButtonActionPerformed(evt);
            }
        });

        deleteTaskButton.setText("Delete Task");
        deleteTaskButton.setEnabled(false);
        deleteTaskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTaskButtonActionPerformed(evt);
            }
        });

        addTaskNameLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        addTaskNameLabel.setText("Title");

        AddTaskkDescriptionLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        AddTaskkDescriptionLabel.setText("Description");

        taskPriorityLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        taskPriorityLabel.setText("Task Priority");

        taskDueDateLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        taskDueDateLabel.setText("Due Date");

        addTasksLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        addTasksLabel.setText("Add Tasks");

        editTasksLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        editTasksLabel.setText("Edit Tasks");

        searchTaskLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        searchTaskLabel.setText("Title");

        searchTaskField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTaskFieldActionPerformed(evt);
            }
        });

        taskGroupDLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N

        taskGroupHeaderLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 36)); // NOI18N
        taskGroupHeaderLabel.setText("TASK GROUP");

        backButton.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        backButton.setText("<< Go Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(taskGroupDescriptionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(markCompleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(deleteTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTaskLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchTaskField))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(taskPriorityLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(taskDueDateLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addTaskNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddTaskkDescriptionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(taskNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dueDateField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(taskDescriptionField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(taskPrioritySlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))))
                .addGap(805, 805, 805))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addTasksLabel)
                                .addGap(432, 432, 432)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(descriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(categoryLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(taskGroupNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(taskGroupDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)))
                            .addComponent(sortTasksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                        .addComponent(taskGroupHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTaskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editTasksLabel))
                .addGap(376, 376, 376)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(53, 53, 53)
                        .addComponent(addTasksLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taskNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addTaskNameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taskDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddTaskkDescriptionLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dueDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskDueDateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taskPriorityLabel)
                            .addComponent(taskPrioritySlider, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(addTaskButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editTasksLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchTaskField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchTaskLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(markCompleteButton)
                            .addComponent(deleteTaskButton))
                        .addGap(128, 128, 128)
                        .addComponent(sortTasksButton)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(taskGroupHeaderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taskGroupDescriptionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(categoryLabel)
                            .addComponent(taskGroupNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descriptionLabel)
                            .addComponent(taskGroupDLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskButtonActionPerformed
        // TODO add your handling code here:                
        Task newTask = new Task(this.taskNameField.getText(),this.taskDescriptionField.getText(),this.taskPrioritySlider.getValue(),this.dueDateField.getText());
        this.taskGroup.addTask(newTask);     
        this.printTasksTextArea.setText(taskGroup.printTask());
        this.taskNameField.setText("");
        this.taskDescriptionField.setText("");
        this.dueDateField.setText("");        
        this.addTaskButton.setEnabled(false);
    }//GEN-LAST:event_addTaskButtonActionPerformed

    private void sortTasksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortTasksButtonActionPerformed
        // TODO add your handling code here:
        this.taskGroup.sortTaskByPriority();        
        this.printTasksTextArea.setText(this.taskGroup.printTask());
    }//GEN-LAST:event_sortTasksButtonActionPerformed

    private void markCompleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markCompleteButtonActionPerformed
        // TODO add your handling code here:
        this.taskGroup.getTaskByName(this.searchTaskField.getText()).setIsComplete(true);
        this.printTasksTextArea.setText(this.taskGroup.printTask());
        searchTaskField.setText("");
    }//GEN-LAST:event_markCompleteButtonActionPerformed

    private void taskNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskNameFieldActionPerformed
        // TODO add your handling code here:
        addTaskButton.setEnabled(true);
    }//GEN-LAST:event_taskNameFieldActionPerformed

    private void searchTaskFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTaskFieldActionPerformed
        // TODO add your handling code here:
        this.markCompleteButton.setEnabled(true);
        this.deleteTaskButton.setEnabled(true);
    }//GEN-LAST:event_searchTaskFieldActionPerformed

    private void deleteTaskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTaskButtonActionPerformed
        // TODO add your handling code here:
        this.taskGroup.removeTask(this.searchTaskField.getText());
        this.printTasksTextArea.setText(this.taskGroup.printTask());
        searchTaskField.setText("");
    }//GEN-LAST:event_deleteTaskButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:        
        tasksFrame tf = new tasksFrame(user);
        this.setVisible(false);
        this.dispose();
        tf.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddTaskkDescriptionLabel;
    private javax.swing.JButton addTaskButton;
    private javax.swing.JLabel addTaskNameLabel;
    private javax.swing.JLabel addTasksLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JButton deleteTaskButton;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JTextField dueDateField;
    private javax.swing.JLabel editTasksLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton markCompleteButton;
    private javax.swing.JTextArea printTasksTextArea;
    private javax.swing.JTextField searchTaskField;
    private javax.swing.JLabel searchTaskLabel;
    private javax.swing.JButton sortTasksButton;
    private javax.swing.JTextField taskDescriptionField;
    private javax.swing.JLabel taskDueDateLabel;
    private javax.swing.JLabel taskGroupDLabel;
    private javax.swing.JLabel taskGroupDescriptionLabel;
    private javax.swing.JLabel taskGroupHeaderLabel;
    private javax.swing.JLabel taskGroupNameLabel;
    private javax.swing.JTextField taskNameField;
    private javax.swing.JLabel taskPriorityLabel;
    private javax.swing.JSlider taskPrioritySlider;
    // End of variables declaration//GEN-END:variables
}
