/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrea
 */
public class tasksFrame extends javax.swing.JFrame {
    private User user;
    private String newTaskGroupName;
    private String newTaskGroupDescription;
    private boolean newTaskGroupNameDone = false;
    private boolean newTaskGroupDescriptioDone = false;
    public TaskGroup taskGroupToBePassed;
    

    /**
     * Creates new form tasksFrame
     */
    public tasksFrame() {
        initComponents();
    }

    tasksFrame(User newUser) {
        this.user = newUser;
        initComponents();
        this.helloLabel.setText("Hello, " + user.getUserName()); 
        this.printTaskGroupsArea.setText(user.getTaskGroupList().printTaskGroups());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        jPopupMenu6 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        popupMenu2 = new java.awt.PopupMenu();
        jTextField1 = new javax.swing.JTextField();
        helloLabel = new javax.swing.JLabel();
        menuLabel1 = new javax.swing.JLabel();
        addNewTaskGroupButton = new javax.swing.JButton();
        SetCategoryNameLabel = new javax.swing.JLabel();
        setCategoryNameField = new javax.swing.JTextField();
        SetCategoryDescriptionLabel = new javax.swing.JLabel();
        setCategoryDescriptionField = new javax.swing.JTextField();
        addNewTaskGroupLabel = new javax.swing.JLabel();
        editTaskGroupLabel = new javax.swing.JLabel();
        taskGroupNameSearchLabel = new javax.swing.JLabel();
        taskGroupCategoryNameSearchField = new javax.swing.JTextField();
        deleteTaskGroupButton = new javax.swing.JButton();
        renameTaskGroupButton = new javax.swing.JButton();
        taskGroupChangeDescriptionButton = new javax.swing.JButton();
        newTaskGroupNameTextField = new javax.swing.JTextField();
        newDescriptionTextField = new javax.swing.JTextField();
        openTaskGroupButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        printTaskGroupsArea = new javax.swing.JTextArea();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        popupMenu1.setLabel("popupMenu1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        popupMenu2.setLabel("popupMenu2");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("To Do List | Menu |");

        helloLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        helloLabel.setText("Hello,");

        menuLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        menuLabel1.setText("What would you like to do?");

        addNewTaskGroupButton.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        addNewTaskGroupButton.setText("Add a new Task Group");
        addNewTaskGroupButton.setActionCommand("AddTaskGroupChoiceButton");
        addNewTaskGroupButton.setEnabled(false);
        addNewTaskGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewTaskGroupButtonActionPerformed(evt);
            }
        });

        SetCategoryNameLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        SetCategoryNameLabel.setText("Name of the Category:");
        SetCategoryNameLabel.setInheritsPopupMenu(false);

        setCategoryNameField.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        setCategoryNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCategoryNameFieldActionPerformed(evt);
            }
        });

        SetCategoryDescriptionLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        SetCategoryDescriptionLabel.setText("Description of the Category:");
        SetCategoryDescriptionLabel.setInheritsPopupMenu(false);

        setCategoryDescriptionField.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        setCategoryDescriptionField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        setCategoryDescriptionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setCategoryDescriptionFieldActionPerformed(evt);
            }
        });

        addNewTaskGroupLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
        addNewTaskGroupLabel.setText("Create a new Task Group");

        editTaskGroupLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
        editTaskGroupLabel.setText("Edit an existing Task Group");

        taskGroupNameSearchLabel.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        taskGroupNameSearchLabel.setText("Name of the Category");

        taskGroupCategoryNameSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskGroupCategoryNameSearchFieldActionPerformed(evt);
            }
        });

        deleteTaskGroupButton.setText("Delete");
        deleteTaskGroupButton.setEnabled(false);
        deleteTaskGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTaskGroupButtonActionPerformed(evt);
            }
        });

        renameTaskGroupButton.setText("Rename");
        renameTaskGroupButton.setEnabled(false);
        renameTaskGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameTaskGroupButtonActionPerformed(evt);
            }
        });

        taskGroupChangeDescriptionButton.setText("Change Description");
        taskGroupChangeDescriptionButton.setEnabled(false);
        taskGroupChangeDescriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskGroupChangeDescriptionButtonActionPerformed(evt);
            }
        });

        newTaskGroupNameTextField.setEditable(false);
        newTaskGroupNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newTaskGroupNameTextFieldActionPerformed(evt);
            }
        });

        newDescriptionTextField.setEditable(false);
        newDescriptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDescriptionTextFieldActionPerformed(evt);
            }
        });

        openTaskGroupButton.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        openTaskGroupButton.setText("Open Taks Group");
        openTaskGroupButton.setEnabled(false);
        openTaskGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openTaskGroupButtonActionPerformed(evt);
            }
        });

        printTaskGroupsArea.setEditable(false);
        printTaskGroupsArea.setColumns(20);
        printTaskGroupsArea.setRows(5);
        jScrollPane2.setViewportView(printTaskGroupsArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addNewTaskGroupLabel)
                                        .addComponent(SetCategoryDescriptionLabel)
                                        .addComponent(setCategoryNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SetCategoryNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(setCategoryDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(menuLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addNewTaskGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(taskGroupChangeDescriptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(newDescriptionTextField))
                                    .addComponent(taskGroupNameSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editTaskGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteTaskGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(renameTaskGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(newTaskGroupNameTextField))
                                    .addComponent(openTaskGroupButton, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                    .addComponent(taskGroupCategoryNameSearchField)))
                            .addComponent(helloLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(menuLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNewTaskGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editTaskGroupLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetCategoryNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taskGroupNameSearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(taskGroupCategoryNameSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteTaskGroupButton)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(renameTaskGroupButton)
                            .addComponent(newTaskGroupNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taskGroupChangeDescriptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openTaskGroupButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(setCategoryNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SetCategoryDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setCategoryDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addNewTaskGroupButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void addNewTaskGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewTaskGroupButtonActionPerformed
        // TODO add your handling code here:        
        TaskGroup newTaskGroup = new TaskGroup(newTaskGroupName, newTaskGroupDescription);
        this.user.getTaskGroupList().addTaskGroup(newTaskGroup);        
        addNewTaskGroupButton.setEnabled(false);         
        this.setCategoryNameField.setText("");
        this.setCategoryDescriptionField.setText(""); 
        this.printTaskGroupsArea.setText(user.getTaskGroupList().printTaskGroups());
    }//GEN-LAST:event_addNewTaskGroupButtonActionPerformed

    private void setCategoryNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCategoryNameFieldActionPerformed
        // TODO add your handling code here:
        this.newTaskGroupName = setCategoryNameField.getText();   
        this.newTaskGroupNameDone = true;        
        if(this.newTaskGroupNameDone && this.newTaskGroupDescriptioDone){
            addNewTaskGroupButton.setEnabled(newTaskGroupNameDone);
        }
    }//GEN-LAST:event_setCategoryNameFieldActionPerformed

    private void setCategoryDescriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setCategoryDescriptionFieldActionPerformed
        // TODO add your handling code here:
        this.newTaskGroupDescription = setCategoryDescriptionField.getText();
        this.newTaskGroupDescriptioDone = true;
        if(this.newTaskGroupNameDone && this.newTaskGroupDescriptioDone){
            addNewTaskGroupButton.setEnabled(newTaskGroupNameDone);
        }
    }//GEN-LAST:event_setCategoryDescriptionFieldActionPerformed

    private void taskGroupCategoryNameSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskGroupCategoryNameSearchFieldActionPerformed
        // TODO add your handling code here:        
        this.renameTaskGroupButton.setEnabled(true);
        this.deleteTaskGroupButton.setEnabled(true);
        this.taskGroupChangeDescriptionButton.setEnabled(true);
        this.openTaskGroupButton.setEnabled(true);        
    }//GEN-LAST:event_taskGroupCategoryNameSearchFieldActionPerformed

    private void deleteTaskGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTaskGroupButtonActionPerformed
        // TODO add your handling code here:        
        user.getTaskGroupList().removeTaskGoup(taskGroupCategoryNameSearchField.getText());        
        this.taskGroupCategoryNameSearchField.setText("");
        this.deleteTaskGroupButton.setEnabled(false);
        this.renameTaskGroupButton.setEnabled(false);
        this.taskGroupChangeDescriptionButton.setEnabled(false);
        this.printTaskGroupsArea.setText(user.getTaskGroupList().printTaskGroups());
    }//GEN-LAST:event_deleteTaskGroupButtonActionPerformed

    private void renameTaskGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameTaskGroupButtonActionPerformed
        // TODO add your handling code here:
        this.taskGroupCategoryNameSearchField.setEditable(false);
        this.newTaskGroupNameTextField.setEditable(true);     
        this.printTaskGroupsArea.setText(user.getTaskGroupList().printTaskGroups());
    }//GEN-LAST:event_renameTaskGroupButtonActionPerformed

    private void newTaskGroupNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newTaskGroupNameTextFieldActionPerformed
        // TODO add your handling code here:
        this.user.getTaskGroupList().editTaskGroupName(this.taskGroupCategoryNameSearchField.getText(), this.newTaskGroupNameTextField.getText());
        this.taskGroupCategoryNameSearchField.setEditable(true);
        this.newTaskGroupNameTextField.setEditable(false);       
        this.taskGroupCategoryNameSearchField.setText("");
        this.newTaskGroupNameTextField.setText("");        
        this.deleteTaskGroupButton.setEnabled(false);
        this.renameTaskGroupButton.setEnabled(false);
        this.taskGroupChangeDescriptionButton.setEnabled(false);
        this.printTaskGroupsArea.setText(user.getTaskGroupList().printTaskGroups());
    }//GEN-LAST:event_newTaskGroupNameTextFieldActionPerformed

    private void taskGroupChangeDescriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskGroupChangeDescriptionButtonActionPerformed
        // TODO add your handling code here:
        this.taskGroupCategoryNameSearchField.setEditable(false);
        this.newDescriptionTextField.setEditable(true);   
        this.printTaskGroupsArea.setText(user.getTaskGroupList().printTaskGroups());
    }//GEN-LAST:event_taskGroupChangeDescriptionButtonActionPerformed

    private void newDescriptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDescriptionTextFieldActionPerformed
        // TODO add your handling code here:
        this.user.getTaskGroupList().editTaskGroupDescription(this.taskGroupCategoryNameSearchField.getText(), this.newDescriptionTextField.getText());
        this.taskGroupCategoryNameSearchField.setEditable(true);
        this.newDescriptionTextField.setEditable(false);       
        this.taskGroupCategoryNameSearchField.setText("");
        this.newDescriptionTextField.setText("");
        this.deleteTaskGroupButton.setEnabled(false);
        this.renameTaskGroupButton.setEnabled(false);
        this.taskGroupChangeDescriptionButton.setEnabled(false);
        this.printTaskGroupsArea.setText(user.getTaskGroupList().printTaskGroups());        
    }//GEN-LAST:event_newDescriptionTextFieldActionPerformed

    private void openTaskGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openTaskGroupButtonActionPerformed
        // TODO add your handling code here:        
        taskFrame2 tf2 = new taskFrame2(this.user.getTaskGroupList().getTaskGroupByName(this.taskGroupCategoryNameSearchField.getText()), this.user);
        this.setVisible(false);
        this.dispose();
        tf2.setVisible(true);
    }//GEN-LAST:event_openTaskGroupButtonActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SetCategoryDescriptionLabel;
    private javax.swing.JLabel SetCategoryNameLabel;
    private javax.swing.JButton addNewTaskGroupButton;
    private javax.swing.JLabel addNewTaskGroupLabel;
    private javax.swing.JButton deleteTaskGroupButton;
    private javax.swing.JLabel editTaskGroupLabel;
    private javax.swing.JLabel helloLabel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JPopupMenu jPopupMenu6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel menuLabel1;
    private javax.swing.JTextField newDescriptionTextField;
    private javax.swing.JTextField newTaskGroupNameTextField;
    private javax.swing.JButton openTaskGroupButton;
    private java.awt.PopupMenu popupMenu1;
    private java.awt.PopupMenu popupMenu2;
    private javax.swing.JTextArea printTaskGroupsArea;
    private javax.swing.JButton renameTaskGroupButton;
    private javax.swing.JTextField setCategoryDescriptionField;
    private javax.swing.JTextField setCategoryNameField;
    private javax.swing.JTextField taskGroupCategoryNameSearchField;
    private javax.swing.JButton taskGroupChangeDescriptionButton;
    private javax.swing.JLabel taskGroupNameSearchLabel;
    // End of variables declaration//GEN-END:variables
}
